
first: 200
last: 281
template: ./tmp/targs_%d.

# Measured from Mark's dumbbell, R.I.P.
dumbbell:
    length: 35
    weight: 0.5

# Set 'free' to some false value (like 'no') if you want the calibration
# for any camera to remain constant while the other cameras move.
initial:    
    - ori_file: config/dumbbell/cam1.tif.ori
      addpar_file: config/dumbbell/cam1.tif.addpar
      free: yes

    - ori_file: config/dumbbell/cam2.tif.ori
      addpar_file: config/dumbbell/cam2.tif.addpar
      free: yes

    - ori_file: config/dumbbell/cam3.tif.ori
      addpar_file: config/dumbbell/cam3.tif.addpar
      free: yes

    - ori_file: config/dumbbell/cam4.tif.ori
      addpar_file: config/dumbbell/cam4.tif.addpar
      free: yes 

scene:
    flags: hp, headers
    image_size: [ 1280, 1024 ]
    pixel_size: [ 0.014, 0.014 ]

    # Multimedia parameters:
    cam_side_n: 1  # air
    object_side_n: 1.33  # perspex
    wall_ns: [ 1.43 ]
    wall_thicks: [ 5 ]
